### ISSUE TITLE
https and other security features

### ISSUE THREAD

**Issue by tinyCodersDen** [kethan1/Blogger101-website#2]
Hello @kethan1,

Viper here, use openSSL for better security enhancements and certificates, OpenSSL uses private keys to store encrypted data. For more information, see [here](https://stackoverflow.com/questions/29458548/can-you-add-https-functionality-to-a-python-flask-web-server).

**Comment by kethan1** [comment]
Heroku provided https. The site already redirects from http to https. No need to work about this.

**Comment by tinyCodersDen** [comment]
Ok, didn't see the redirect, if that's the case then it's fine

**Comment by kethan1** [comment]
The HTTP request could, emphasizing could, be intercepted, and the user could be returned malicious code, but we shouldn't need to worry about this.

**Comment by tinyCodersDen** [comment]
Yes.. the redirect seems to solve most of the issue
