### ISSUE TITLE
reCAPTCHA 

### ISSUE THREAD

**Issue by tinyCodersDen** [kethan1/Blogger101-website#6]
The website protects using https, but it doesn't prevent ddos attacks and bots, to stop this, try implementing reCAPTCHA as a site improvement. [If you want to know more about reCAPTCHA](https://www.google.com/recaptcha/about/)

**Comment by kethan1** [comment]
Will probably add reCAPTCHA for login. There is not much of a point to add Recaptcha to when the user enters the site, so I will also add rate-limiting and more

**Comment by tinyCodersDen** [comment]
Ya, what I mean is, when people sign up, that will act as the first line of defence against bots and ddos attacks. Signing up is a big thing for the reCaptcha, but not for the login as we already know that the users are humans. One more recommendation is that reCaptcha should be done automatically during login, this will ensure nobody is "brute forcing" people's passwords. It is also recommended that if somebody has the correct username, but has the wrong password, and they get it wrong 3-5 times, you automatically stop them from logging in, or send an email to verify that it's them. It will make the system more modern. I will close this for now, but if you have any issues, open it again.

**Comment by kethan1** [comment]
sadly we have an API for login. The API needs to be upgraded to use API tokens

**Comment by tinyCodersDen** [comment]
Oh, well I think you can just add the API only for the signup feature. During login, you can just use a basic counter or some python to count how much somebody tries to brute force the passwords. This won't require an API at all because you only use it for 
signup, and not log in. This is generally what google does when someone tries to brute force passwords.
