### ISSUE TITLE
Secure Password Storage

### ISSUE THREAD

**Issue by tinyCodersDen** [kethan1/Blogger101-website#8]
Currently, the program stores plaintext passwords in the database. Sometimes, this dangerous practice can be hacked if a hacker intercepts your MongoDB database. Consider using [password hashing](https://en.wikipedia.org/wiki/Cryptographic_hash_function) instead. This is a modern practice for securing passwords rather than them being stored as plaintext. Consider using [passlib](https://pypi.org/project/passlib/) and other python modules used for encryption. Passlib has a lot of hashing algorithms, but I suggest sha_256 or sha_512 as they are more secure than other hashing algorithms.

**Comment by kethan1** [comment]
Yeah, this had been on my radar for a while, I just haven't gotten around to it. Expect an update in the next week

**Comment by tinyCodersDen** [comment]
Sure. If you need any help with any password hashing, I can help you out with how it works. For now, I will close the issue.

**Comment by kethan1** [comment]
okay, I have pushed a commit that adds password hashing and a ton of other good stuff.
